// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC74QUXD9vtuk3_MG_2Tc4UcCB1AwOACq0',
    appId: '1:199318782238:web:fba52276dae8ee6cadc90f',
    messagingSenderId: '199318782238',
    projectId: 'zego-test-cc687',
    authDomain: 'zego-test-cc687.firebaseapp.com',
    storageBucket: 'zego-test-cc687.firebasestorage.app',
    measurementId: 'G-GBP7RXF58F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBekkkY3uPKsN09m6pppFG9zN81DXJTkIQ',
    appId: '1:199318782238:android:6fa9e8b4815255f9adc90f',
    messagingSenderId: '199318782238',
    projectId: 'zego-test-cc687',
    storageBucket: 'zego-test-cc687.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE670aJWvSQB23ScORxtZBzXwp08I_Sqc',
    appId: '1:199318782238:ios:799d67966d1315ebadc90f',
    messagingSenderId: '199318782238',
    projectId: 'zego-test-cc687',
    storageBucket: 'zego-test-cc687.firebasestorage.app',
    iosBundleId: 'com.example.zegoCallingFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE670aJWvSQB23ScORxtZBzXwp08I_Sqc',
    appId: '1:199318782238:ios:799d67966d1315ebadc90f',
    messagingSenderId: '199318782238',
    projectId: 'zego-test-cc687',
    storageBucket: 'zego-test-cc687.firebasestorage.app',
    iosBundleId: 'com.example.zegoCallingFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC74QUXD9vtuk3_MG_2Tc4UcCB1AwOACq0',
    appId: '1:199318782238:web:415c428eff827180adc90f',
    messagingSenderId: '199318782238',
    projectId: 'zego-test-cc687',
    authDomain: 'zego-test-cc687.firebaseapp.com',
    storageBucket: 'zego-test-cc687.firebasestorage.app',
    measurementId: 'G-G9LRXV6REJ',
  );
}
